// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(RepositoryPatternDbContext))]
    [Migration("20191012192445_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new { Id = 1, City = "Skopje", Email = "martinp@iborn.net", FirstName = "Martin", LastName = "Panovski" },
                        new { Id = 2, City = "Skopje", Email = "petrep@iborn.net", FirstName = "Petre", LastName = "Petrevski" },
                        new { Id = 3, City = "Ohrid", Email = "martinp@iborn.net", FirstName = "Mite", LastName = "Mitevski" },
                        new { Id = 4, City = "Strumica", Email = "jovanj@iborn.net", FirstName = "Jovan", LastName = "Jovanovski" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
